name: novella
description: Novella - Discover millions of books
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_spinkit: ^5.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  epub_view: ^3.2.0
  dio: ^5.9.0
  xml2json: ^6.2.3
  cached_network_image: ^3.4.1
  sembast: ^3.8.5
  sembast_web: ^2.4.0
  path_provider: ^2.1.4
  path: ^1.9.0
  go_router: ^14.6.2
  uuid: ^4.5.1
  intl: ^0.20.2
  share_plus: ^10.0.3
  url_launcher: ^6.3.1
  file_picker: ^8.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
